linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - goconst
    - goimports
    - gocyclo
    - gocognit

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 5
  gocyclo:
    min-complexity: 35
  gocognit:
    min-complexity: 50

run:
  timeout: 5m
  issues-exit-code: 1

issues:
  exclude-dirs:
    - vendor
    - docs
