// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: listings/listings.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortField int32

const (
	SortField_SORT_FIELD_UNSPECIFIED SortField = 0
	SortField_SORT_FIELD_CREATED_AT  SortField = 1
	SortField_SORT_FIELD_PRICE       SortField = 2
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_FIELD_UNSPECIFIED",
		1: "SORT_FIELD_CREATED_AT",
		2: "SORT_FIELD_PRICE",
	}
	SortField_value = map[string]int32{
		"SORT_FIELD_UNSPECIFIED": 0,
		"SORT_FIELD_CREATED_AT":  1,
		"SORT_FIELD_PRICE":       2,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_listings_listings_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_listings_listings_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{0}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_listings_listings_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_listings_listings_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{1}
}

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_listings_listings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listings_listings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateListingRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetListingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Пагинация
	Page    uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage uint32 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Сортировка
	SortBy    SortField `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=listings.SortField" json:"sort_by,omitempty"`
	SortOrder SortOrder `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=listings.SortOrder" json:"sort_order,omitempty"`
	// Фильтрация по цене
	MinPrice      *float32 `protobuf:"fixed32,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float32 `protobuf:"fixed32,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_listings_listings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listings_listings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListingsRequest) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetListingsRequest) GetSortBy() SortField {
	if x != nil {
		return x.SortBy
	}
	return SortField_SORT_FIELD_UNSPECIFIED
}

func (x *GetListingsRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *GetListingsRequest) GetMinPrice() float32 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *GetListingsRequest) GetMaxPrice() float32 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

type ListingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Price          float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,6,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsOwner        bool                   `protobuf:"varint,8,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_listings_listings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listings_listings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{2}
}

func (x *ListingResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ListingResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingResponse) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *ListingResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListingResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type ListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ListingResponse     `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       uint32                 `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingsResponse) Reset() {
	*x = ListingsResponse{}
	mi := &file_listings_listings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingsResponse) ProtoMessage() {}

func (x *ListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listings_listings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingsResponse.ProtoReflect.Descriptor instead.
func (*ListingsResponse) Descriptor() ([]byte, []int) {
	return file_listings_listings_proto_rawDescGZIP(), []int{3}
}

func (x *ListingsResponse) GetListings() []*ListingResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *ListingsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListingsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListingsResponse) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListingsResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_listings_listings_proto protoreflect.FileDescriptor

const file_listings_listings_proto_rawDesc = "" +
	"\n" +
	"\x17listings/listings.proto\x12\blistings\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xae\x01\n" +
	"\x14CreateListingRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18dR\x05title\x12,\n" +
	"\vdescription\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\n" +
	"\x18\xe8\aR\vdescription\x12%\n" +
	"\timage_url\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\bimageUrl\x12 \n" +
	"\x05price\x18\x04 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x05price\"\xb3\x02\n" +
	"\x12GetListingsRequest\x12\x1d\n" +
	"\x04page\x18\x01 \x01(\rB\t\xfaB\x06*\x04\x18d \x00R\x04page\x12$\n" +
	"\bper_page\x18\x02 \x01(\rB\t\xfaB\x06*\x04\x182 \x00R\aperPage\x12,\n" +
	"\asort_by\x18\x03 \x01(\x0e2\x13.listings.SortFieldR\x06sortBy\x122\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x13.listings.SortOrderR\tsortOrder\x12,\n" +
	"\tmin_price\x18\x05 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05-\x00\x00\x00\x00H\x00R\bminPrice\x88\x01\x01\x12,\n" +
	"\tmax_price\x18\x06 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00H\x01R\bmaxPrice\x88\x01\x01B\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"\x8b\x02\n" +
	"\x0fListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12'\n" +
	"\x0fauthor_username\x18\x06 \x01(\tR\x0eauthorUsername\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bis_owner\x18\b \x01(\bR\aisOwner\"\xaf\x01\n" +
	"\x10ListingsResponse\x125\n" +
	"\blistings\x18\x01 \x03(\v2\x19.listings.ListingResponseR\blistings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\rR\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\rR\n" +
	"totalPages*X\n" +
	"\tSortField\x12\x1a\n" +
	"\x16SORT_FIELD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SORT_FIELD_CREATED_AT\x10\x01\x12\x14\n" +
	"\x10SORT_FIELD_PRICE\x10\x02*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x022\xf1\x04\n" +
	"\x0fListingsService\x12\xb0\x02\n" +
	"\rCreateListing\x12\x1e.listings.CreateListingRequest\x1a\x19.listings.ListingResponse\"\xe3\x01\x92A\xc8\x01\x122Создание нового объявления\x1a\x91\x01Создает новое объявление с указанным заголовком, текстом, изображением и ценой\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/listings\x12\xaa\x02\n" +
	"\vGetListings\x12\x1c.listings.GetListingsRequest\x1a\x1a.listings.ListingsResponse\"\xe0\x01\x92A\xc8\x01\x122Получение ленты объявлений\x1a\x91\x01Возвращает ленту объявлений с возможностью сортировки, фильтрации и пагинации\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/listingsB\xf1\x01\x92A\xc0\x01\x12\x86\x01\n" +
	"\x18Marketplace Listings API\x12cAPI для управления и просмотра объявлений маркетплейса2\x051.0.0\x1a\x0elocalhost:8080*\x01\x012\x10application/json:\x10application/jsonZ+github.com/Snake1-1eyes/marketplace/pkg/apib\x06proto3"

var (
	file_listings_listings_proto_rawDescOnce sync.Once
	file_listings_listings_proto_rawDescData []byte
)

func file_listings_listings_proto_rawDescGZIP() []byte {
	file_listings_listings_proto_rawDescOnce.Do(func() {
		file_listings_listings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listings_listings_proto_rawDesc), len(file_listings_listings_proto_rawDesc)))
	})
	return file_listings_listings_proto_rawDescData
}

var file_listings_listings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_listings_listings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_listings_listings_proto_goTypes = []any{
	(SortField)(0),                // 0: listings.SortField
	(SortOrder)(0),                // 1: listings.SortOrder
	(*CreateListingRequest)(nil),  // 2: listings.CreateListingRequest
	(*GetListingsRequest)(nil),    // 3: listings.GetListingsRequest
	(*ListingResponse)(nil),       // 4: listings.ListingResponse
	(*ListingsResponse)(nil),      // 5: listings.ListingsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_listings_listings_proto_depIdxs = []int32{
	0, // 0: listings.GetListingsRequest.sort_by:type_name -> listings.SortField
	1, // 1: listings.GetListingsRequest.sort_order:type_name -> listings.SortOrder
	6, // 2: listings.ListingResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: listings.ListingsResponse.listings:type_name -> listings.ListingResponse
	2, // 4: listings.ListingsService.CreateListing:input_type -> listings.CreateListingRequest
	3, // 5: listings.ListingsService.GetListings:input_type -> listings.GetListingsRequest
	4, // 6: listings.ListingsService.CreateListing:output_type -> listings.ListingResponse
	5, // 7: listings.ListingsService.GetListings:output_type -> listings.ListingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_listings_listings_proto_init() }
func file_listings_listings_proto_init() {
	if File_listings_listings_proto != nil {
		return
	}
	file_listings_listings_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listings_listings_proto_rawDesc), len(file_listings_listings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listings_listings_proto_goTypes,
		DependencyIndexes: file_listings_listings_proto_depIdxs,
		EnumInfos:         file_listings_listings_proto_enumTypes,
		MessageInfos:      file_listings_listings_proto_msgTypes,
	}.Build()
	File_listings_listings_proto = out.File
	file_listings_listings_proto_goTypes = nil
	file_listings_listings_proto_depIdxs = nil
}
